In [4]:
# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rnd

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier

In [7]:
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

In [9]:
train_df.describe()

,A,B,C,D,E,F,G,H,I,J,...,T,U,V,W,X,Y,Z,AA,AB,AC
count,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,...,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000,13814.000000
mean,6907.500000,98.630375,4.551904,21.069756,40.403839,19.584244,40.881499,21.418166,39.798476,19.960589,...,18.594411,41.955006,5.717090,755.119577,82.581077,4.358236,38.892657,2.755081,24.997152,24.997152
std,3987.902644,106.209951,8.616680,1.242105,3.555143,1.485123,3.255742,1.465726,3.126425,1.469368,...,1.417519,3.928012,4.148212,8.029338,12.322477,2.646731,12.922950,3.684821,14.542283,14.542283
min,1.000000,10.000000,0.000000,16.790000,31.426667,16.100000,30.160000,17.200000,32.626667,15.100000,...,14.890000,32.730000,-5.000000,729.300000,44.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,3454.250000,50.000000,0.000000,20.290000,37.700000,18.566667,38.663333,20.390000,37.500000,19.100000,...,17.700000,38.933333,2.833333,750.166667,74.333333,2.000000,28.666667,0.200000,12.505481,12.505481
50%,6907.500000,60.000000,0.000000,21.200000,40.090000,19.500000,40.966667,21.390000,39.090000,20.100000,...,18.426667,41.230000,5.666667,755.500000,86.000000,4.000000,40.000000,2.833333,24.858659,24.858659
75%,10360.750000,100.000000,10.000000,22.000000,43.133333,20.600000,43.427679,22.390000,42.254000,21.000000,...,19.700000,44.590000,8.800000,761.400000,92.130952,6.000000,42.000000,5.416667,37.755971,37.755971
max,13814.000000,910.000000,70.000000,24.100000,63.360000,24.600000,50.363333,26.700000,50.163333,23.760000,...,23.840000,53.326667,19.700000,772.300000,100.000000,14.000000,66.000000,11.400000,49.996530,49.996530